name: easy_book
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  intl: ^0.17.0
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.19
  flutter_riverpod: ^2.4.6
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  sign_in_with_apple: ^6.0.0

flutter:
  uses-material-design: true
